language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - git config --global user.name "tianzx"
  - git config --global user.email "tianzx@aliyun.com"
script:
  # 生成静态文件
  - npm run build
after_script:
  # 将生成的静态文件，初始化为 git 仓库
  - cd public
  - git init
  - git config user.name "tianzx"
  - git config user.email "tianzx@aliyun.com"
  - git add --all
  - git commit -m "push from the travis server"
  # 推送到 blog-html 分支
  - git push --force  "https://${GH_Token}@${GH_REF}" master:blog-html
after_success:
  - echo "success"
env:
  global:
    - GH_REF: github.com/tianzx/blog.git
    - secure: "cDXYj938ZLjVmEgXaRNDXLTQzrU066ZjZYsMrayUzo5k/2e8u+1APItH/PL0w5hnfkh3UrVHXIiRTBIY46od/tfxFDPOwHyiK3kDFVHC+n0UEmEOiuqsYJnB7cxwq7y5Lai77ouu6ZSmGIz1Zd4oVJlPeWBBWbZifaLIukXpEM83s5S+ZTxUymGUJ4eUT1qG6XP47hPBaQhAU4QzovEfdQ+N3jZJgTPXmmDas4s6/pmPNeWajUdRoHA1vq4TsCskTqlbPV6MCxg7lq34lqAi4FN24+fpZNCSqdrOsmLJmn7beXbN2v2vJBwTMa1Oiq4s2naBpgfDVJRW69x6s5yBg5YnhQP8FuVLcS4RCBdTebrwXJ7rf5p0G91OHcOUD7MdCWYtbXt9pVpVVA9lpJIKwZwdcRNf9vV17gtMAjSh/5cG7TfFVPeMvwFoIK7zoHJBT9DtJgdOXgxUeMgenQEt1/FAnPz+CRJWE8rEvtNPb2pemy6axjVnUTPW6GQ4Yk382oOfAvVmEjqCJec65UfL3+KOlYXEyZyOY52db/3E6TjWDyCOa9ba0BU6WYwVWSiXpxDKcdY2GBh61eE4mHgF3ySFBs0AfEZI3P59QQK2aWp/sWuLyx/DWbRy7YieJqOjGsRnRI4BNFFI/A+kcRSXHVEK9XwLScISyN/H5rmWPB0="